# Generated by Django 4.1.7 on 2023-02-25 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_artist_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='spotify_id',
            field=models.CharField(default=None, max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
