# Generated by Django 4.1.7 on 2023-02-26 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_artist_spotify_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Song',
            new_name='Track',
        ),
        migrations.RenameField(
            model_name='musicpreferencesprofile',
            old_name='songs',
            new_name='track',
        ),
    ]
