# Generated by Django 3.2.18 on 2023-03-02 19:12

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20230301_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='image',
            field=models.ImageField(null=True, upload_to=profiles.models.get_file_path),
        ),
        migrations.DeleteModel(
            name='Match',
        ),
    ]
